-- CREATE TABLE IF NOT EXISTS topic (
-- − id int SERIAL PRIMARY KEY,
-- − title varchar(255) NOT NULL,
-- − description varchar(255)
-- − additionalSource varchar(255)
-- − complete bit
-- − creationDate - datetime
-- − completionDate - datetime
-- );
--
--
--
--
-- − id int SERIAL PRIMARY KEY,
-- − title varchar(255) NOT NULL,
-- − description varchar(255)
-- − additionalSource varchar(255)
-- − complete bit
-- − creationDate - datetime
-- − completionDate - datetime
